In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("C:\\Users\\amitm\\Desktop\\basic ml project\\data\\fourth_clean.csv")

In [3]:
numeric_df = df.select_dtypes(include=['number'])

In [4]:
numeric_df.corr()['Price']

Ram              0.743007
Weight           0.210370
Price            1.000000
TouchScreen      0.191226
IPS              0.252208
PPI              0.473487
HDD             -0.096441
SSD              0.670799
Hybrid           0.007989
Flash_Storage   -0.040511
Name: Price, dtype: float64

In [5]:
df.drop(columns = ['Hybrid','Flash_Storage'],inplace=True)

In [6]:
df['Gpu brand'] = df['Gpu'].apply(lambda x:x.split()[0])

In [7]:
df = df[df['Gpu brand']!='ARM']

In [8]:
df.head(2)

,Company,TypeName,Ram,Gpu,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Gpu brand
0,Apple,Ultrabook,8,Intel Iris Plus Graphics 640,macOS,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,Intel
1,Apple,Ultrabook,8,Intel HD Graphics 6000,macOS,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,Intel

In [9]:
df = df.drop(columns=['Gpu'])

In [10]:
def setcategory(text):
    
    if text=='Windows 10' or text=='Windows 7' or text=='Windows 10 S':
        return 'Windows'
    
    elif text=='Mac OS X' or text=='macOS':
        return 'Mac'
    
    else:
        return 'Other'

In [11]:
df['OpSys'] = df['OpSys'].apply(lambda x:setcategory(x))

In [12]:
df.head(2)

,Company,TypeName,Ram,OpSys,Weight,Price,TouchScreen,IPS,PPI,CPU_name,HDD,SSD,Gpu brand
0,Apple,Ultrabook,8,Mac,1.37,71378.6832,0,1,226.983005,Intel Core i5,0,128,Intel
1,Apple,Ultrabook,8,Mac,1.34,47895.5232,0,0,127.677940,Intel Core i5,0,0,Intel

In [13]:
df.to_csv("C:\\Users\\amitm\\Desktop\\basic ml project\\data\\final_clean.csv", index=False)